name: Deploy on Branch Merge

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build NestJS App
        run: npm run build

      - name: Build Docker image
        run: docker build -t diucsealumni/api:${{ github.ref_name }} .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push diucsealumni/api:${{ github.ref_name }}

      # Optional: Clean up dangling docker images
      - name: Prune old Docker images
        run: docker image prune -f

      # Upload .env to Dev server
      - name: Upload .env to Dev server
        if: github.ref == 'refs/heads/dev'
        run: scp .env ${{ secrets.DEV_SERVER }}:/home/ubuntu/app/.env

      - name: Deploy via SSH (Dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          ssh ${{ secrets.DEV_SERVER }} "
            docker pull diucsealumni/api:dev &&
            docker rm -f devapp || true &&
            docker run -d --restart=always --name devapp -p 3000:3000 --env-file /home/ubuntu/app/.env diucsealumni/api:dev
          "

      # Upload .env to Test server
      - name: Upload .env to Test server
        if: github.ref == 'refs/heads/test'
        run: scp .env ${{ secrets.TEST_SERVER }}:/home/ubuntu/app/.env

      - name: Deploy via SSH (Test)
        if: github.ref == 'refs/heads/test'
        run: |
          ssh ${{ secrets.TEST_SERVER }} "
            docker pull diucsealumni/api:test &&
            docker rm -f testapp || true &&
            docker run -d --restart=always --name testapp -p 3000:3000 --env-file /home/ubuntu/app/.env diucsealumni/api:test
          "

      # Upload .env to Production server
      - name: Upload .env to Prod server
        if: github.ref == 'refs/heads/main'
        run: scp .env ${{ secrets.PROD_SERVER }}:/home/ubuntu/app/.env

      - name: Deploy via SSH (Main)
        if: github.ref == 'refs/heads/main'
        run: |
          ssh ${{ secrets.PROD_SERVER }} "
            docker pull diucsealumni/api:main &&
            docker rm -f prodapp || true &&
            docker run -d --restart=always --name prodapp -p 3000:3000 --env-file /home/ubuntu/app/.env diucsealumni/api:main
          "
